version: "3.9"

services: 
  app:
    container_name: app
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}